# Default values for kong_platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kong:
  ingressController:
    enabled: true
    installCRDs: false

  postgresql:
    enabled: false

  env:
    database: "off"

  proxy:
    http:
      nodePort: 31080
    tls:
      nodePort: 31443


