apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ric-ingress-a1mediator
spec:
  rules:
  - http:
      paths:
      - path: /a1mediator
        backend:
          serviceName: {{ include "common.servicename.a1mediator" . }}
          servicePort: {{ .Values.httpservice.port }}
