#
# ==================================================================================
#   Copyright (c) 2019 Nokia
# ==================================================================================
#

{{ if (eq .Values.ricapp.appconfig.override "") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ if .Values.ricapp.appconfig.override }}{{ .Values.ricapp.appconfig.override }}{{ else }}{{ .Release.Name }}-appconfig{{ end }}
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
{{ end }}
